services:
  mc:
    image: itzg/minecraft-bedrock-server:latest
    container_name: servidormc
    ports:
      - "19132:19132/tcp"
      - "19132-19140:19132-19140/udp"
    environment:
      EULA: "TRUE"
      GAMEMODE: "survival"
      DIFFICULTY: "hard"
      SERVER_NAME: "Hybridge Bedrock Server"
      MAX_PLAYERS: "40"
      ALLOW_CHEATS: "false"
      ONLINE_MODE: "true"
      WHITE_LIST: "false"
      TRANSPORT: "nethernet"
      SERVER_UDP_PORTS: "19132-19140"
      TZ: "America/Mexico_City"
    volumes:
      - "./data:/data"
    restart: unless-stopped
